/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CampaignContract } from "./Campaign";
import { CampaignFactoryContract } from "./CampaignFactory";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Campaign"): CampaignContract;
      require(name: "CampaignFactory"): CampaignFactoryContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { CampaignContract, CampaignInstance } from "./Campaign";
export {
  CampaignFactoryContract,
  CampaignFactoryInstance,
} from "./CampaignFactory";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
