/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type NewContract = ContractEventLog<{
  _from: string;
  _campaign: string;
  _valueGoal: string;
  0: string;
  1: string;
  2: string;
}>;

export interface CampaignFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CampaignFactory;
  clone(): CampaignFactory;
  methods: {
    campaignAddresses(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    createCampaign(
      _name: string,
      _description: string,
      _imageUrl: string,
      _valueGoal: number | string | BN
    ): NonPayableTransactionObject<void>;

    getCampaigns(): NonPayableTransactionObject<string[]>;

    getCampaignsLength(): NonPayableTransactionObject<string>;
  };
  events: {
    NewContract(cb?: Callback<NewContract>): EventEmitter;
    NewContract(
      options?: EventOptions,
      cb?: Callback<NewContract>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "NewContract", cb: Callback<NewContract>): void;
  once(
    event: "NewContract",
    options: EventOptions,
    cb: Callback<NewContract>
  ): void;
}
